#!/usr/bin/env python3

import hashlib
from pathlib import Path


FONT_GROUPS = {
    "NOTOSERIF_12_FONT_ID": (
        "notoserif_12_regular.h", "notoserif_12_bold.h",
        "notoserif_12_bolditalic.h", "notoserif_12_italic.h",
    ),
    "NOTOSERIF_14_FONT_ID": (
        "notoserif_14_regular.h", "notoserif_14_bold.h",
        "notoserif_14_bolditalic.h", "notoserif_14_italic.h",
    ),
    "NOTOSERIF_16_FONT_ID": (
        "notoserif_16_regular.h", "notoserif_16_bold.h",
        "notoserif_16_bolditalic.h", "notoserif_16_italic.h",
    ),
    "NOTOSERIF_18_FONT_ID": (
        "notoserif_18_regular.h", "notoserif_18_bold.h",
        "notoserif_18_bolditalic.h", "notoserif_18_italic.h",
    ),
    "NOTOSANS_12_FONT_ID": (
        "notosans_12_regular.h", "notosans_12_bold.h",
        "notosans_12_bolditalic.h", "notosans_12_italic.h",
    ),
    "NOTOSANS_14_FONT_ID": (
        "notosans_14_regular.h", "notosans_14_bold.h",
        "notosans_14_bolditalic.h", "notosans_14_italic.h",
    ),
    "NOTOSANS_16_FONT_ID": (
        "notosans_16_regular.h", "notosans_16_bold.h",
        "notosans_16_bolditalic.h", "notosans_16_italic.h",
    ),
    "NOTOSANS_18_FONT_ID": (
        "notosans_18_regular.h", "notosans_18_bold.h",
        "notosans_18_bolditalic.h", "notosans_18_italic.h",
    ),
    "UI_10_FONT_ID": ("ubuntu_10_regular.h", "ubuntu_10_bold.h"),
    "UI_12_FONT_ID": ("lexenddeca_12_regular.h", "lexenddeca_12_bold.h"),
    "UI_14_FONT_ID": ("lexenddeca_14_regular.h", "lexenddeca_14_bold.h"),
    "UI_18_FONT_ID": ("lexenddeca_18_regular.h", "lexenddeca_18_bold.h"),
    "SMALL_FONT_ID": ("notosans_8_regular.h",),
}


def normalized_digest(path: Path) -> int:
    data = path.read_bytes().replace(b"\r\n", b"\n")
    return int(hashlib.sha256(data).hexdigest(), 16)


def font_id(font_dir: Path, files: tuple[str, ...]) -> int:
    value = sum(normalized_digest(font_dir / name) for name in files)
    return value % (2**32) - (2**31)


def main() -> None:
    font_dir = Path(__file__).resolve().parent.parent / "builtinFonts"
    print("// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh")
    print("#pragma once\n")
    for name, files in FONT_GROUPS.items():
        print(f"#define {name} ({font_id(font_dir, files)})")

    print('\n// Font ID 0 is reserved as the "not found" sentinel.')
    print("// Guard against any hash accidentally producing 0.")
    for name in FONT_GROUPS:
        print(f'static_assert({name} != 0, "Font ID collision with sentinel");')


if __name__ == "__main__":
    main()
